### ISSUE TITLE
Flagsmith's `loadingState.error` is not respect actual error state

### ISSUE THREAD

**Issue by ok2ju** [Flagsmith/flagsmith-js-client#185] opened 2023-09-11 14:53 UTC
Hello, Flagsmith team. We run into the issue when `loadingState.error` is not reflect actual state.

Preconditions:
- flagsmith api is not responded for some reason;

We expecting in that situation that `loadingState.error` will contain actual error but it's actually always `null`. Is it a bug or expected behaviour? If it is expected then how to get actual error in that situation?

```js
const flagsmith = useFlagsmith();
const loadingState = useFlagsmithLoading();

const isError = flagsmith.loadingState?.error; // is always null
loadingState.error // is always null
```

**Comment by novakzaballa** [comment] 2023-09-11 22:55
Are you working with version 18 of React? If that is the case, probably this issue is a duplicate of React.

**Comment by ok2ju** [comment] 2023-09-13 08:49
@novakzaballa yes, you are right, we are using React 18.

**Comment by ok2ju** [comment] 2023-09-20 06:59
Hey, @novakzaballa 👋 Maybe do you have ETA for this fix? It will be really helpful for us to understand how to proceed with this. Thanks.

**Comment by ok2ju** [comment] 2023-09-25 18:35
Hey, @novakzaballa . Thanks for the info. Yes, I've seen this workaround but I'm afraid that I cannot use it. But anyway thanks. Just let me know when issue will be resolved. Huge thanks 👍

**Comment by dabeeeenster** [comment] 2023-09-25 18:44
Sure, I will. Best regards.

**Comment by dabeeeenster** [comment] 2023-10-04 17:38
PR created: https://github.com/Flagsmith/flagsmith/pull/2828

**Comment by novakzaballa** [comment] 2023-10-10 21:26
@ok2ju we have this PR ready for review https://github.com/Flagsmith/flagsmith-js-client/pull/188. We had a solution before but it was not working with certain scenarios, i.e. with the NextJS example. Hopefully, we'll merge these changes soon.

**Closed** 2023-10-13 14:35 UTC

**Comment by ok2ju** [comment] 2023-10-16 10:42
Hello, @novakzaballa, @kyle-ssg . I've just upgraded to `v3.20.0` and it looks like the issue is still exist.
How I tested it:
1. in Chrome DevTools block api request to flagsmith (like `/api/v1/flags`);
2. trying to log `flagsmith. loadingState` from `useFlagsmith` hook and also `loadingState` from `useFlagsmithLoading` hook.

Both hooks responds with the same values and `isFetching`, `isLoading` and `error` are always the same (`true`, `true`, `null`).

**Comment by novakzaballa** [comment] 2023-10-16 16:23
Hi @ok2ju, I am sorry to hear that you still have issues with even with the new version of the API. We tested these changes with our current examples and React v18, and they all worked as expected. Could you please provide a minimal project with code showing how this version fails?
As soon as we receive your code we will verify it, start working on a fix, and re-open this issue if needed.

**Comment by matthewelwell** [comment] 2023-10-18 08:58
Thanks for confirming @ok2ju !
