### ISSUE TITLE
Rollup Name for react

### ISSUE THREAD

**Issue by mbellish** [Flagsmith/flagsmith-js-client#192] opened 2023-10-24 16:33 UTC
Could we get a rollup name that's more standard than flagsmith/react ?  It's hard to alias that in webpack or rollup as a global variable.
Something like flagsmith-react?

**Comment by cbix** [comment] 2023-11-23 21:53
Not sure if this is related, but I'm getting this webpack error:
```
ERROR in ./node_modules/flagsmith/src/react.tsx 16:70
Module parse failed: Unexpected token (16:70)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import {IFlagsmith, IFlagsmithTrait, IFlagsmithFeature, IState} from './types'
| 
> export const FlagsmithContext = createContext<IFlagsmith<string,string> | null>(null)
| export type FlagsmithContextType = {
|     flagsmith: IFlagsmith // The flagsmith instance
 @ ./node_modules/flagsmith/react.js 1:78-94
 @ ./src/app/pages/Dashboard/index.tsx 14:0-64 44:18-26 60:25-44
ERROR in ./node_modules/flagsmith/src/react.tsx 16:70
Module parse failed: Unexpected token (16:70)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import {IFlagsmith, IFlagsmithTrait, IFlagsmithFeature, IState} from './types'
| 
> export const FlagsmithContext = createContext<IFlagsmith<string,string> | null>(null)
| export type FlagsmithContextType = {
|     flagsmith: IFlagsmith // The flagsmith instance
 @ ./node_modules/flagsmith/react.js 1:78-94
 @ ./src/app/pages/Dashboard/index.tsx 14:0-64 44:18-26 60:25-44
```
This never happened before and I'm using lots of other typescript dependencies.

**Comment by matthewelwell** [comment] 2023-11-24 11:01
Thanks @mbellish we'll look into this and get back to you.

**Comment by cbix** [comment] 2023-11-24 11:08
Regarding my webpack error, I found the issue is I had
```
modules: ['node_modules', 'src']
```
in my webpack config so webpack was looking at `flagsmith/src` for module resolution. This is fixed by changing it to
```
modules: ['node_modules', path.resolve(__dirname, '../../src')]
```
so only the desired `src` directory is considered.

**Comment by novakzaballa** [comment] 2023-11-24 13:35
Thank you for the update @cbix !
@mbellish is it possible that are having a similar issue? As a workaround to verify if this is the case you could also manually delete the src code in the node_modules/flasmith directory after install the packages or add this `postinstall` to your pacake.json scripts section:
`    "postinstall": "rm -rf ./node_modules/flagsmith/src"
`

**Comment by mbellish** [comment] 2023-11-25 18:05
It's a different situation. We have a number of modules which use a webpack configuration to build as a module, and in order to desginate this as an external library (not to be included in the compiled results). the "flagsmith/react" was problematic.

We ended up forking the codebase and changing the umd name from flagsmith/react to flagsmith-react in the rollup.config.ts line  165:
            name:"flagsmith/react",

**Closed** 2024-02-07 13:55 UTC
