### ISSUE TITLE
isLoading never updates to false

### ISSUE THREAD

**Issue by amirabuhasan** [Flagsmith/flagsmith-js-client#184] opened 2023-09-11 05:42 UTC
Hi!

We recently updated from using React's `render` to `createRoot` as part of our migration to React 18. However, this caused the `isLoading` property retrieved from the `useFlagsmithLoading` hook to never update from true to false. Here's the code:

```
// App.tsx

import { useFlagsmithLoading } from 'flagsmith/react';

export default function App() {
  const flagsmithLoading = useFlagsmithLoading();

  return (
     <>
         {flagsmithLoading.isLoading ? (
          <Loading />
        ) : ( 
          <div>[The rest of the App is rendered here]</div> 
        )}
     </>
  )
}
```

We currently initialise flagsmith according to the docs: 

```
// index.tsx

import flagsmith from 'flagsmith';

const container = document.getElementById('root');
const root = ReactDOMClient.createRoot(container!);

root.render(
  <React.StrictMode>
        <FlagsmithProvider
          flagsmith={flagsmith}
          options={{
            environmentID: FLAGSMITH_API_KEY,
            cacheFlags: false,
            api: 'https://api.flagsmith.com/api/v1/', <--- we are not on the Edge API if that changes anything
          }}
        >
            <App />
        </FlagsmithProvider>
  </React.StrictMode>
);
```

We are currently on `3.19.1`. I tried updating to `3.18.5-beta7` after seeing this issue: https://github.com/Flagsmith/flagsmith-js-client/issues/174, but it doesn't seem to have solved it either. Just to add on a bit, the same setup was working perfectly on React 18 with `ReactDOMClient.render` instead of `ReactDOMClient.createRoot`. Let me know if you need any additional details from my end.

**Comment by novakzaballa** [comment] 2023-09-11 22:53
Thank you for reporting this issue, We were able to reproduce the behavior with React 18. We will start working on a solution and keep this issue updated with our findings and progress.

**Comment by novakzaballa** [comment] 2023-09-12 19:12
It seems like the root cause of the issue with the latest version of React (18) is the new checks in strict mode https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-strict-mode.

> This feature will give React better performance out-of-the-box, but requires components to be resilient to effects being mounted and destroyed multiple times.

Removing the StrictMode wrapper from the App component is a workaround. Also, in prod mode those checks should not be an issue.

I will continue trying to find the exact offending lines, probably this portion of the code is one of the https://github.com/Flagsmith/flagsmith-js-client/blob/3cbf741198f9a7415e9bf2be0e7b175e553ce3d8/react.tsx#L27 parts that are against that new policy being checked in strict mode now at dev time.

**Closed** 2023-10-13 14:35 UTC
